.PHONY: setup
setup:
		pyenv local 3.8.5
		python -m venv .venv
		.venv/bin/python -m pip install --upgrade pip
		.venv/bin/python -m pip install -r requirements.txt


		cd .. ; git clone git@github.com:ourownstory/neural_prophet.git
		cd neural_prophet
		pip install .
		cd ..
		cd Capstone-Project-Rossman-Sales